[package]
name = "vex-python-preprocessor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
argmap = "1.1.2"
semver = "1.0.21"
serde_json = "1.0"
tempfile = "3.9.0"
